services:
  backend:
    build:
      target: run
      context: .
    ports:
      - "8080:8080"

  database:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty12
      POSTGRES_DB: latte_gallery
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
